global:
  domain: argocd.example.com # make sure to point this domain to your ingress controller 
repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi            
server:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    ingressClassName: nginx # make sure to use the same ingress class name as in your ingress controller
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-issuer-dev" # look /infra/certificates/cluster-issuer.yaml
    tls: true

configs:
  params:
    server.insecure: true