# get a look on this doc
# https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: < API Token >